Doist/todoist-api-typescript

- .github/workflows/CI.yml
I’ve noticed `CI.yml` workflow file referencing `secrets.GH_PACKAGES_TOKEN`, which should not be used in this public repository.
After having removed the reference, GitHub package registry was still being used, which I tracked down to wrong setup in `setup-node` action.
> ci: Remove reference to unused secret.

- .github/workflows/CI.yml
- .github/workflows/publish.yml
Based on historical data, clamped between 5 and 60.
See https://github.com/Doist/Issues/issues/5259
> build: set sensible timout

- package-lock.json
- package.json
- src/restClient.test.ts
- src/testUtils/mocks.ts
I don't quite understand the reason for using `jest-mock-extended` package, but the way we are currently using it is definitely wrong. In particular, `isAxiosError` implementation performs a `Boolean(...)` conversion. `Boolean(Function)` is `true`, so it is incorrectly depended upon that `isAxiosError(mock<AxiosError>().isAxiosError) === true`, while `isAxiosError ` is really undefined.
I propose that we remove `jest-mock-extended` package until we really need it, and simply use type casted placeholder objects instead.
> refactor: Remove jest-mock-extended, fix test.

- src/restClient.test.ts
- src/restClient.ts
`axios` has a `baseURL` configuration parameter that should be used instead of constructing absolute URL manually. This lets us remove of of two places in which `urljoin` is used.
> refactor: Remove urljoin in favour of baseURL configuration parameter.

- package-lock.json
- package.json
- src/TodoistApi.ts
Continued from https://github.com/Doist/todoist-api-typescript/pull/60. Completely remove `url-join` dependency.
Please note that `url-join` was used incorrectly - it expected the first argument to be baseURL, not partial path. Other than that, we are now doing [the same thing](https://github.com/jfromaniello/url-join/blob/88bad0fa91216e9b199cb3962009d67ae681d6fb/lib/url-join.js#L47) it did, minus unnecessary processing we don't need.
`TodoistApi.*.test` tests are pretty comprehensive, so this should be safe.
> refactor: Remove `url-join` dependency.

- package-lock.json
- package.json
Bumping the version to 1.6 to ensure all the dependency updates that have been done recently go out to those who may not be able to update as quickly to v2 when that comes out.
> chore: Bumping the version to 1.6

- package-lock.json
- package.json
- src/TodoistApi.comments.test.ts
- src/TodoistApi.labels.test.ts
- src/TodoistApi.projects.test.ts
- src/TodoistApi.sections.test.ts
- src/TodoistApi.tasks.test.ts
- src/TodoistApi.ts
- src/authentication.test.ts
- src/authentication.ts
- src/consts/endpoints.ts
This adds a new, optional, API surface that allows the consumer to dictate whether they want to access the staging APIs. By default, if not present, it will revert to the production API. Getting staging data is fully opt-in.
> chore: Adds support for accessing Todoist via a baseUrl

- .gitignore
- package-lock.json
- package.json
- src/TodoistApi.comments.test.ts
- src/TodoistApi.labels.test.ts
- src/TodoistApi.projects.test.ts
- src/TodoistApi.sections.test.ts
- src/TodoistApi.tasks.test.ts
- src/TodoistApi.ts
- src/testUtils/testDefaults.ts
- src/types/entities.ts
Fixes: #133 
Fields that weren't being returned in v1 of the REST API may now be returned but have a value of `null`. Our validation wasn't catering for that. Have updated the partial types to accept the type or NULL.
There were a few other instances of number-based ID usage that hadn't been switched. These have now been corrected.
You can try and follow the instructions in the readme using the `scratch.ts` file in order to test this.
``` typescript
import { TodoistApi } from './TodoistApi'
const token = '<TOKEN>'
const api = new TodoistApi(token)
async function doIt() {
try {
const projects = await api.getProjects()
console.log(projects.length)
} catch (error: unknown) {
if (error instanceof Error) {
console.log(error)
}
console.log({ error })
}
}
doIt().catch(() => {
// noop
})
```
I …
> refactor: Accept nulls for optional entity fields

- package-lock.json
- package.json
- src/types/requests.ts
In the `GetTasksArgs` type there was one remaining field using numbers instead of strings, that of `ids`.
> chore: Corrects one final id number type

- package-lock.json
- package.json
- src/TodoistApi.projects.test.ts
- src/TodoistApi.ts
- src/restClient.axios.test.ts
- src/restClient.test.ts
- src/restClient.ts
Fixes: https://github.com/Doist/todoist-api-typescript/issues/131
The problem with passing in just an array of objects into axios is it may not do what we're expecting it to do when it comes to formatting. This was exactly what was happening. 
In this PR I'm adding a custom `paramsSerializer` function to ensure that formatting is as we want it.
You can try this out with the `scratch.ts` file (see readme for usage). Make sure you set your token and a couple of task IDs for your account.
With this fix, you will get just those two tasks returned, prior to this fix, it would have returned _all_ your tasks.
``` Typescript
import { TodoistApi } from './TodoistApi'
const token = '<TOKEN>'
const api = new TodoistApi(token)
async function doIt() {
try {
const tasks = await api.getTasks({
ids: …
```
> fix: Corrects the call when an array of ids is used

- package-lock.json
- package.json
- src/types/requests.ts
When updating a task via the Todoist API SDK, we want to be able to unset the `assignee_id` field. Following the documentation (https://developer.todoist.com/rest/v2/#update-a-task) this can be done by passing in the `null` value. This PR is to allow for said `null` value to be passed as well.
We want to do the same thing for the `dueString` field (and all the other `due`-related fields).
This is needed for our new Task Helper UI Extension (https://github.com/Doist/event-integrations/pull/1117).
> fix: Allow passing null assigneeId and dueString to unset field

- package.json
- src/types/entities.ts
While working on https://github.com/Doist/integrations-backlog/issues/418 (upgrade `Todoist-Outlook` to API v2), I've noticed that some of the errors and test failures looks something like:
```
Type '{ ...; }' is not assignable to type 'EntityInHierarchyWithIndent'.
Type '{ ...; }' is not assignable to type 'Partial<EntityInHierarchy>'.
Types of property 'parentId' are incompatible.
Type 'string | null | undefined' is not assignable to type 'number | undefined'.
Type 'null' is not assignable to type 'number | undefined'.
```
Since the API v2 now treats all `id`s as strings (i.e. `projectId`s, `sectionId`s, `taskId`s, etc.), it makes sense to change this `EntityInHierarchy.parentId` to string as well.
This is apparently only used in `Todoist-Outlook` …
> fix: Change EntityInHierarchy.parentId to string

- package.json
- src/types/entities.ts
Follow up to https://github.com/Doist/todoist-api-typescript/pull/157, as `parentId` should be allowed a `null` value as well.
> fix: Allow null values for EntityInHierarchy.parentId

- package.json
- src/types/entities.ts
- src/utils/colors.test.ts
- src/utils/colors.ts
While working on upgrading `Todoist-Outlook` to Todoist API v2 by leveraging `todoist-api-typescript` v2 (https://github.com/Doist/Todoist-Outlook/pull/609), I've noticed that we don't currently have a way to retrieve a `Color` object (https://github.com/Doist/todoist-api-typescript/blob/main/src/types/entities.ts#L149-L153) via its "internal name", which is what is saved in the `Project.color` field.
As an example, there's no way to map "berry_red" to a `Color`.
This PR adds a utility function that does that (+ some simple tests).
Blocks https://github.com/Doist/Todoist-Outlook/pull/609
We (briefly?) considered restructuring the `Color` type so that its `name` would map to the "internal name" (i.e. "berry_red") and `displayName` to its... errr... display name (i.e. "Berry Red"). However, …
> feat: Add getColorByInternalName utility function

- package-lock.json
- package.json
Added `type-fest` as peer dependency to fix types relying on it (closes #254).
Additionally, bumped `type-fest` to latest version, since there are no breaking changes.
> chore: add `type-fest` as peer dependency to fix types relying on it

- src/consts/endpoints.ts
- src/restClient.test.ts
- src/restClient.ts
This PR introduces changes to the `restClient` module to handle POST requests to the sync API endpoint differently. 
Resolves #257 
- Export the `API_SYNC_BASE_URI` constant from the `endpoints` module to make it accessible in other modules
- Modify the `request` function in `restClient` to skip generating a random request ID for POST requests to the sync API endpoint
- Add a test case in `restClient.test.ts` to verify that a random request ID is not created for POST requests to the sync API endpoint
The sync API endpoint does not allow a request ID in the CORS headers. To accommodate this, the `request` function now checks if the `baseUri` includes the `API_SYNC_BASE_URI` before generating a random request ID for POST requests. This ensures that POST requests to the sync API endpoint do …
> fix: remove request id when calling the sync api

- README.md
- src/TodoistApi.comments.test.ts
- src/TodoistApi.labels.test.ts
- src/TodoistApi.projects.test.ts
- src/TodoistApi.sections.test.ts
- src/TodoistApi.tasks.test.ts
- src/TodoistApi.ts
- src/authentication.test.ts
- src/consts/endpoints.ts
- src/restClient.test.ts
- src/restClient.ts
- src/testUtils/testDefaults.ts
- src/types/entities.ts
- src/types/requests.ts
- src/utils/taskConverters.test.ts
- src/utils/taskConverters.ts
In line with ongoing internal efforts, this PR refactors the SDK to serve as an intermediary between consumers and the [Todoist Sync API](https://developer.todoist.com/sync/v9/#overview), replacing the [Todoist REST API](https://developer.todoist.com/rest/v2/#overview).
The SDK API remains largely unchanged, with the following exceptions:
- Some new properties have been added to entities.
- Certain existing properties have been marked as required.
- The following methods are now **paginated**:
```plaintext
- getTasks
- getProjects
- getProjectCollaborators
- getSections
- getLabels
- getSharedLabels
- getComments
```
This refactor ensures compatibility with the latest version of the Todoist Sync API while maintaining the familiar client API interface for consumers.
- Passing the `ids` …
> feat: [BREAKING] migrate from REST API to Sync API

- .github/workflows/deploy-docusaurus.yml
Adding github workflow to `main` to deploy the pre-release `v4` branch documentation website to  GitHub pages.
> docs: deploy docusaurus website to github pages

- src/TodoistApi.ts
- src/consts/endpoints.ts
- src/restClient.test.ts
- src/restClient.ts
- src/types/requests.ts
- src/types/sync.ts
This PR adds the ability to be able to move tasks.
Under the hood, this is actually using a sync command rather than the REST/Sync API. This is basically missing functionality as it can't be done via the REST API. 
This was requested from https://github.com/Doist/todoist-api-typescript/issues/265
Fixes https://github.com/Doist/todoist-api-typescript/issues/265
I'm doing this against the v4 branch as v4 has so many breaking changes, doing this in main seemed daft.
> feat: Add moveTasks function

- src/TodoistApi.comments.test.ts
- src/testUtils/testDefaults.ts
- src/types/entities.ts
- src/utils/validators.test.ts
Although in https://github.com/Doist/todoist-api-typescript/pull/276 the API version was updated to v9.220, we missed that in v.214 several properties of Section and Comment objects sent by the backend changed.
> fix: Update Section and Comment schemas to match API v9.214 changes

- src/TodoistApi.projects.test.ts
- src/TodoistApi.tasks.test.ts
- src/TodoistApi.ts
- src/testUtils/testDefaults.ts
- src/types/entities.ts
- src/utils/projectConverter.ts
- src/utils/taskConverters.ts
- src/utils/validators.ts
This schema def fixes the issue I encountered when using GetProjects and better matches the API docs for the [project response](https://todoist.com/api/v1/docs#tag/Projects/operation/get_projects_api_v1_projects_get)
This change makes tests in the repository fail.
Task entity also needs to be aligned
Maybe the typing needs to be adjusted. Only tested that it no longer threw Zod Errors.
> fix: map updated API task and project objects to match local schemas

- src/utils/taskConverters.ts
Fixes https://github.com/Doist/todoist-api-typescript/issues/290
Ensures that the creatorId field is not null.
> chore: Ensures that `creatorId` is not null

- src/restClient.axios.test.ts
- src/restClient.ts
When making a GET request, any values that come through as `null` should not be serialised as they will essentially become strings of `'null'` when going to the backend. 
Fixes https://github.com/Doist/todoist-api-typescript/issues/292
> chore: Do not serialise null/undefined values for GET calls

- src/TodoistApi.ts
- website/docs/api/classes/TodoistApi.md
- website/docs/api/type-aliases/Permission.md
`requestId` does not guarantee idempotency. Setting this field just customizes the `X-Request-ID` HTTP header, which can be useful for things like logging.
> docs: change API methods  description

- .eslintrc.json
- src/TodoistApi.moveTasks.test.ts
- src/TodoistApi.ts
- Closes #310 
- Found while working on https://github.com/Doist/todoist-ai/pull/22
See the linked issue #310 for all the details, including additional information about what the fix is, which is what's implemented in this PR.
This PR also includes new tests for `moveTasks`, beyond testing this very issue. This is because there were no tests for `moveTasks` before this work here. I decided to submit them in a new file because the file for task-related tests is already big enough.
> fix: use different UUIDs for each move task command

- src/TodoistApi.labels.test.ts
Added tests for shared label endpoints: getSharedLabels, renameSharedLabel, and removeSharedLabel. The tests check both the API call and the result.
> Add shared label tests

- src/TodoistApi.sections.test.ts
- src/testUtils/testDefaults.ts
- src/types/entities.ts
- src/utils/urlHelpers.ts
- Added a helper function to create URLs for sections  
- Updated the section entity to include a `url` property  
- Added tests to check that section URLs are correct
> Add section URL helpers and tests
